name: cpplint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --filter=
    - run: cpplint --filter=-build,-legal,-readability,-runtime,-whitespace --recursive .
